<?php

return [
    "index" => "About Us",
    "message_from_co_founders" => [
        "title" => "Mensaje de los Co-Fundadores",
        "subtitle1" => "Estimados/as Amigos/as,",   
        "p1" => "Cada año, Epro 360 les da la bienvenida a estudiantes que ambicionan un futuro brillante y único. Todos nuestros profesionales, en su mayoría antiguos estudiantes internacionales, se levantan cada mañana con el deseo de guiar, asesorar y formar a todos estos estudiantes que aceptan el desafío de estudiar en el exterior y convertirse en la nueva generación de líderes globales. El éxito llama al éxito dentro de la comunidad Epro 360.",
        "subtitle2" => "Un Toque Personal ",
        "p2" => "Nuestros Mentores Educativos y Asesores Profesionales, que actúan a través de la Red Epro 360, son personas con un historial de excelencia académica y profesional alcanzados en un ámbito global. Ellos son la prueba fehaciente de que una educación bien equilibrada y con un carácter marcado global prepara a los estudiantes no sólo para un éxito personal, sino también profesional. A diferencia de todos los competidores, Epro 360 es muchísimo más que un servicio de colocación del estudiante en un programa de estudios en el extranjero. Nuestro equipo de trabajo ha estado en la piel del futuro estudiante internacional y conoce de primera mano el proceso que denominamos “inflación académica.” Inflación académica describe el valor decreciente de un diploma universitario en el mundo actual, debido a que cada vez más un mayor porcentaje de personas disponen de uno. Epro 360 combate como ninguna otra compañía contra esta inflación.</em> ",
        "p3" => "",
        "subtitle3" => "¡Mucho Más que Un Diploma Internacional!",
        "p4" => "Creemos que si estás leyendo este texto estás de acuerdo que para convertirse en una persona de éxito, tanto en el plano personal y profesional, se requiere de mucho más que un diploma universitario. Sin embargo, nosotros vamos más allá y creemos firmemente que para ser exitosos en el mundo actual se requiere de Mucho Más que un Título Universitario Internacional. Esta es la razón por la que hemos convertido la idea anterior en nuestro eslogan. A través de un trato personal y cercano, la introducción del concepto innovador de la Red de Mentores y Asesores, y otros muchos servicios adicionales que descubrirás en nuestra página web o consultando con nuestro Embajador más cercano a ti, estamos seguros de que Epro 360 proporciona las mejores herramientas existentes en el mercado para formar a la nueva generación de líderes globales.",
        "subtitle4" => "Lo Mejor de los Dos Mundos",
        "p5" => "",
        "p6" => "Nos gustaría enfatizar en la idea única de combinar lo que algunas empresas hacen por separado y en la mayoría de ocasiones a un precio excesivo. Por un lado, a través de nuestro programa de becas, el estudiante recibirá un asesoramiento personal y profesional que le ayudará a conseguir una beca académica o deportiva en una universidad extranjera, la cual deberá atender sus necesidades y objetivos futuros. Por otro lado, el estudiante recibirá información crucial, que raramente es enseñada dentro del ámbito meramente académico, a través de nuestros Red Epro 360 de Mentores Educativos y Asesores de Carrera. La balanza en todo momento está claramente inclinada a favor de Epro 360 y esperamos que todo estudiante deseoso de éxito sea capaz de comprender el modelo de negocio único que actualmente ofrecemos. <br> <br>  Les saluda cordialmente,"
    ],
    "mission_and_vision"       => [
        "title" => "Nuestra Misión",
        "p1" => "Tenemos una misión clara en Epro 360, la cual es ayudar lo máximo posible a todos aquellos estudiantes a convertirse en personas de éxito,",
        "li1" => "ayudándoles a alcanzar sus sueños profesionales a través del asesoramiento de carrera,",
        "li2" => "proporcionándoles un conocimiento que va más allá de lo enseñado en las instituciones académicas a través del servicio prestado por nuestros Mentores,",
        "li3" => "hacer su educación en el exterior lo más asequible posible, a través del ofrecimiento de becas académicas/atléticas.",
        "subtitle" => "Nuestra Visión",
        "p2" => "La planificación de una carrera exitosa y gratificante en el mundo actual se basa en mucho más que en la obtención de un diploma universitario internacional. Es por eso que Epro 360 monitorea constantemente los rápidos cambios en la educación superior a nivel global. Para dar forma al auténtico líder global del mañana, Epro 360 no se limita a enviar estudiantes al extranjero; Epro 360 los educa e inspira a través de Mentores, Asesores y contenidos educativos de alta calidad y actualizados que no proporciona ningún competidor o entidad educativa.",
        "p3" => "Epro 360 aspira a convertirse en el mayor proveedor global de servicios para la formación académica en el exterior. No solo aspiramos a lo anterior sino que además nos marcamos como objetivo construir la mayor red mundial de profesionales caracterizados por su formación única internacional.",
        "p4" => "",
        "p5" => "",
    ],
    "epro_360_at_a_glance"     => [
        "title" => "Epro 360 en un Simple Vistazo",
        "p1" => "Estos atributos, junto con nuestro deseo de mejorar la vida de los estudiantes internacionales, harán el calendario de Epro 360 ir más allá con incontables momentos de éxito. Esperamos poder seguir agregando contenido al siguiente Calendario.",
        "subtitle" => "La Historia de Epro 360 contada a través de sus hitos",
        "timeline" => [
            "1" => ["month" => "Feb", "year" => "2013", "title" => "Fundación", "text" => "Oswaldo y Christian Chavez en Portoviejo, Ecuador."  ],
            "2" => ["month" => "Jul", "year" => "2013", "title" => "Primeras Presentaciones", "text" => "Proporcionadas a estudiantes de instituto en el área de Portoviejo, Ecuador."  ],
            "3" => ["month" => "Nov", "year" => "2013", "title" => "Expansión", "text" => "Comienzo de prestación de servicios de asesoramiento de carrera y desarrollo personal."  ],
            "4" => ["month" => "Dic", "year" => "2013", "title" => "Primeras presentaciones a nivel internacional", "text" => "Proporcionadas a estudiantes de instituto en Alemania."  ],
            "5" => ["month" => "Ene", "year" => "2014", "title" => "Constitución Nueva Sociedad", "text" => "En Alemania."  ],
            "6" => ["month" => "Mar", "year" => "2014", "title" => "Entrada Nuevo Socio", "text" => "Francisco Galvez se incorpora a Epro 360 como inversor y asesor estratégico."  ],
            "7" => ["month" => "Abr", "year" => "2014", "title" => "Constitución Nueva Sociedad", "text" => "En España."  ],
        ]
    ],
    "what_set_us_apart"        => [
        "title" => "Lo Que Nos Distingue de la Competencia",
        "subtitle1" => "Epro 360 proporciona el mejor valor que nuestro mercado actualmente ofrece.",
        "p1" => "Creemos que la competencia entre participantes dentro de un mismo mercado es tremendamente positiva tanto para los competidores como para los clientes. Esta competencia hace que todos trabajemos más duro y reconsideremos, con mayor frecuencia, lo que realmente queremos ofrecer al mundo. Además, somos conscientes del enorme potencial de muchos estudiantes que carecen de los recursos monetarios para acceder a una formación de calidad. Todo lo anterior nos motiva para mantener un enfoque caracterizado por el ofrecimiento de servicios de alta calidad a un precio razonable e inferior a la mayoría de nuestros competidores.",
        "subtitle2" => "Epro 360 da acceso a infinidad de Becas y Prácticas Laborales personalizadas.",
        "p2" => "Gran parte de la competencia de Epro 360 sólo firma acuerdos de colaboración con una decena de instituciones educativas y siempre oferta la misma beca académica o deportiva al estudiante, independientemente de su situación actual, preferencias personales, u objetivos futuros. En Epro 360 creemos en un servicio único y personal para nuestro cliente. Es por ello que ambicionamos con alcanzar acuerdos de colaboración con un alto porcentaje de las más de cuatro mil universidades en EE.UU. y otras muchas en el resto de países. El estudiante sentirá que es tratado personalmente gracias a nuestro equipo de profesionales, conocedores del mercado y encargados de ofertar becas académicas o deportivas en función de las exclusivas necesidades y objetivos del cliente.",
        "subtitle3" => "Epro 360 ayuda a los estudiantes a aprender sobre ellos mismos.",
        "p3" => "En el mundo global y competitivo actual, no es suficiente con saber sobre \"algo\" o tener una buena educación plasmada en un diploma o título universitario. El estudiante necesita conocerse a sí mismo antes de querer conseguir objetivos mayores como puede ser la consecución de un buen puesto de trabajo. Cuando el estudiante se una a la Comunidad Epro 360, se le proporcionarán herramientas que denominamos de “excavación mental” en forma de seminarios en línea, presentaciones, juegos y videos para ayudarle a encontrarse a sí mismo y encontrar su pasión y su misión en la vida. El estudiante recibirá una amplia gama de herramientas que le permitirán posicionarse de una manera más ventajosa en este mundo tan competitivo, pero a la vez desorientado, en el que vivimos.",
        "subtitle4" => "Epro 360 convierte la complejidad del mundo actual en oportunidad para el estudiante.",
        "p4" => "Epro 360 reproduce, y en ocasiones recluta, a las voces más destacadas del mundo profesional (p. ej. ciencias, negocios, etc.) y educativo con el fin de diseñar una comunidad que permita alimentar a las mentes estudiantiles más exigentes. El señor Ken Robinson, un experto reconocido internacionalmente por su creatividad y experiencia en el mundo educativo, ha mencionado en repetidas ocasiones que, \"nadie sabe cómo el mundo va a ser en el plazo de cinco años; pero sin embargo, todos necesitamos de una educación para sobrevivir en ella.\" ",
        "p5" => "El hecho de saber que una posición actual de trabajo puede incluso no existir en cinco años hace que muchos se estresen y lo llamen decepción o incertidumbre. Sin embargo, Epro 360 lo llama oportunidad y le saca partido a ello ayudando a los estudiantes a conseguir muchísimo más que un título internacional. ",
        "subtitle5" => "El estudiante entrará a formar parte de una red única de profesionales motivados y apasionados por la formación de las nuevas generaciones y que se han enfrentado a los mismos obstáculos que ellos en el pasado.",
        "p6" => "Jeff Hoffman, un exitoso empresario y orador profesional, dice que no se trata ni del método, ni de la meta; todo se resume en las personas con las que uno se relaciona durante el camino de la vida. El estudiante entrará a formar parte de una comunidad de personas que comparten unos mismos valores y objetivos. Ya sea mediante el contacto con otros estudiantes de la misma generación, estudiantes de generaciones anteriores, o mentores o asesores, el estudiante encontrará en la comunidad respuesta a sus a todas sus inquietudes personales y profesionales así como las herramientas necesarias para impulsar su carrera profesional. Toda conexión que se consiga durante una etapa temprana de la vida entre personas que comparten los mismos valores y objetivos, multiplicará su valor en el futuro.  Este marco de aprendizaje más allá del ámbito académico, el establecimiento de conexiones personales y profesionales, la posibilidad de contactar con a líderes del área donde el estudiante desee especializarse, etc. es algo que nadie excepto Epro 360 ofrece. "
    ],
    "epro_360_team"            => [
        "title" => "¿Cúal es la razón de ser de un Embajador Epro 360?",
        "p1" => "Un Embajador Epro 360 hace que el programa de estudios en el extranjero Epro 360, así como el resto de servicios se hagan conocidos en su región. Para ello, el Embajador Epro 360 lleva a cabo tareas de marketing y ventas, participa con regularidad en reuniones con la Gerencia y otros Embajadores a nivel mundial con el objetivo de planificar actividades, etc. Además, es tarea del Embajador coordinar y asesorar al estudiante en todo el proceso de aplicación a la universidad donde el estudiante desee estudiar. El Embajador de Epro 360 es consciente de su extrema importancia dentro de nuestra Organización, ya que es la representación directa de unos valores y una metodología únicos frente a unos clientes también únicos.",
        "subtitle1" => "¡Forma parte de nuestro Equipo!",
        "subtitle2" => "Las tres razones principales por las que es rentable convertirse en Embajador Epro 360.",
        "p2" => "Compensación por encima de la media del sector y basada en resultados dentro de una organización flexible y consciente de tus otras actividades importantes en la vida. Es una posición perfecta para alguien con formación académica, con conocimiento de idiomas, con ambición, con ganas de viajar y conocer gente excelente procedente de todo el mundo. Sabemos que una persona con las características anteriores probablemente dispone ya de una actividad a tiempo completo. Es por ello que estamos abiertos a explorar alternativas para colaborar juntos. Tú realmente te marcas las horas y objetivos que quieres alcanzar. El resto del equipo se encargará de ayudarte a conseguirlos.",
        "p3" => "",
        "p4" => "Conviértete en un mejor comunicador. Gran parte del trabajo que vas a realizar es difundir el mensaje de Epro 360 a todas las personas interesadas en conocernos más allá de lo que la página web pueda difundir. Presentar delante de un grupo de quizás decenas o centenas de estudiantes puede suponer un tremendo obstáculo para comunicarse de manera efectiva para muchos.  Se requiere múltiples habilidades para realizar lo anterior de una manera eficaz. No se preocupe por esto ya que todo el que ha alcanzado el dominio en esta materia ha tropezado cientos de veces. Nosotros te ayudaremos con nuestro equipo de profesionales a prepararte de la mejor manera posible. Un ejemplo de lo anterior es que incluso el guión de nuestras presentaciones será explicado personalmente al embajador por la Gerencia con el objetivo de que el ponente de la presentación se sienta seguro. Esta experiencia y todas las habilidades adquiridas te acompañarán durante toda la vida y te ayudarán tremendamente en el plano personal y profesional.",
        "p5" => "Ayuda a alguien a tener una vida más exitosa. ¿No es esta idea algo genial y que deberían todas las empresas tener en mente? ¿Has oído alguna vez? \"una de las mejores maneras de hacerte feliz es hacer feliz a otra persona.\" Todo el enfoque de Epro 360 gira en torno a hacer felices a toda nuestra Comunidad, en especial a nuestros clientes. Trabajar para Epro 360 es todo un reto que conlleva diversión, adquisición de nuevas habilidades y contactos personales y profesionales, y sobre todo el bienestar de saber que estás ayudando a formar a la nueva generación de líderes globales.",
        "p6" => "Por favor visite nuestra sección de “Careers” para obtener más información sobre esta posición así como otras posiciones actualmente abiertas en Epro 360."
    ],


];