<?php

return [
	"title" => "Material Epro 360 para los Medios",
	"subtitle" => "Epro 360 potencia el valor de la educación universitaria con carácter internacional mediante la adopción de un enfoque único diferente al de cualquier otro competidor.",
	
	"1" => "1. Deterioro continuado del valor de un título académico universitario",
	"p1" => "En los EE.UU. y el resto del mundo, los estudiantes viven actualmente en un mundo caracterizado por una “inflación académica.” El término “Inflación académica” es un término que describe el creciente deterioro de valor asociado a la consecución de un título académico universitario debido en gran parte al incremento de personas que han obtenido o están cursando uno. Por ejemplo, en los EE.UU., muchas personas poseedoras de un título universitario se encuentran subempleadas ya que nunca han podido encontrar un trabajo en el área de estudio en el que se especializaron. Parte de la razón es la proliferación de estudiantes universitarios. De acuerdo con el Instituto de Ciencias de la Educación, entre 2000 y 2010, la cantidad de estudiantes universitarios en los EE.UU. se incrementó en un 37 por ciento, pasando de un total de 15.3 millones a 21 millones. Situación similar ocurre en el resto del mundo.",
	"p2" => "Los estudiantes están actuando en un mercado de rápido crecimiento. En <a href='//www.usnews.com/education/best-colleges/articles/2013/11/11/us-sees-record-number-of-international-college-students'>2013</a>  aproximadamente 800.000 estudiantes llegaron a los EE.UU. para comenzar su andadura como estudiantes internacionales, lo cual significa un aumento superior al 40% en comparación con la década anterior.",
	"p3" => "Epro 360 cree que el problema no es el título universitario en sí o el aumento en el número de estudiantes, sino la falta de inversión por parte del estudiante en su desarrollo personal y profesional. Las estadísticas procedentes de Linkedin.com evidencian que aquellos graduados universitarios que han adquirido experiencia extracurricular significativa y han invertido activamente en su desarrollo personal, son contratados con muchísima más frecuencia y para mejores posiciónes que los que estudiantes que no acometieron dicha inversión. Tener buenas conexiones con profesionales que trabajan en la industria también ayuda tremendamente al estudiante.",
	
	"2" => "2. El enfoque de Epro 360 para combatir la “inflación académica” y la ventaja competitiva proporcionada por Epro 360 a sus estudiantes",
	"p4" => "El enfoque de Epro 360 para ayudar a sus estudiantes internacionales a alcanzar el éxito se materializa a través del ofrecimiento de un completo menú de servicios. Estos servicios incluyen, pero no están limitados a, asesoramiento en torno a la elaboración de un buen currículum, desarrollo del marketing personal del estudiante, programa de pasantías / prácticas laborales, ofrecimiento de la Red Epro 360 que cuenta con mentores educativos y asesores de carrera, etc. Los estudiantes que se unen a la Comunidad Epro 360 tendrán acceso a profesionales que destacan en las industrias que ellos esperan acceder el día de mañana. Estos profesionales, en su mayoría de ellos, antiguos estudiantes internacionales en EE.UU. comparten con los estudiantes las claves de su éxito, consejos académicos y de carrera, y sobre todo responden a las preguntas e inquietudes que el estudiante internacional pueda tener. Todo lo anterior es algo significativamente distinto a lo que viene acostumbrada la industria en la que lo común es cobrar a un estudiante por conseguir únicamente una universidad donde estudiar. Epro 360 es mucho más que un servicio de colocación o emplazamiento y se esfuerza cada día por demostrarlo.",
	"p5" => "Los estudiantes que formen parte de la Comunidad Epro 360 conseguirán obtener una ventaja competitiva frente a aquellos estudiantes fuera de ella o que no inviertan en su desarrollo personal y profesional. Otro apunte para aquellos estudiantes que quieran utilizar su título académico conseguido en los EE.UU. para trabajar en su país de origen o fuera de EE.UU. es la siguiente. Estadísticamente, un título universitario obtenido en los EE.UU., es un activo de alto valor y poco común fuera de los EE.UU. De acuerdo con Tom Jelke, ex Decano Ejecutivo en “Semestre en el Mar,” sólo el 1% de las personas en el mundo actual poseen un título de nivel universitario. El señor Evan M. Ryan, Secretario Adjunto de Estado para Asuntos Educativos y Culturales de los EE.UU. indicó que, \"la educación internacional promueve la construcción de relaciones y el intercambio de conocimientos entre las personas y comunidades en los Estados Unidos y alrededor del mundo, los cuales se antojan como necesarios para resolver los desafíos globales.\" Tomando todo la anterior en conjunto, los servicios educativos ofertados por Epro 360, el dominio del idioma inglés, el título universitario obtenido en EE.UU., y la experiencia enriquecedora personal viviendo en EE.UU., los estudiantes internacionales de Epro 360 tienen una oportunidad única de cambiar su destino.",
	"p6" => "Epro 360 considera todas las ideas mencionadas anteriormente para ofertar una serie de servicios educativos sin parangón en la industria, con el objetivo de proporcionar a sus estudiantes “Mucho más que un Título Internacional,” los cuales les capacitará para alcanzar éxito en el plano personal y profesional.",
	
];