<?php

return [

	"title" => "Preguntas Frecuentes",
	"q1" => "¿Cuándo puedo aplicar?",
	"a1" => "Y Puedes aplicar en cualquier momento. Sólo debes tener en cuenta que el proceso de solicitud podría tomar hasta seis meses. Los semestres académicos  comienzan cada año en agosto y enero. Cuanto antes apliques, mejor. Siempre puedes ponerte en contacto con algún representante de Epro 360 a través de <a href='mailto:info@epro360.com?subject=faq' 'email me'>info@epro360.com</a> o con nuestro Embajador Epro 360 más cercano a ti, para recibir más instrucciones.",
	"q2" => "¿Qué tipo de visa necesito como estudiante en los Estados Unidos?",
	"a2" => "Deberás obtener la visa de estudiante F-1. El personal de Epro 360 te ayudará en el todo el proceso para obtener dicha visa y mucho más.",
	"q3" => "¿Cuáles son los beneficios que la Red Epro 360 realmente me ofrecerá?",
	"a3" => "El objetivo final de la Red Epro 360 es ayudarte a tener éxito en los Estados Unidos a través de un menú completísimo de servicios extracurriculares. Estos incluyen por ejemplo servicio personalizado de marketing online para ayudarte a encontrar el trabajo deseado (p.ej., currículum, linkedin, carta de presentación, etc.), ofertas de pasantías/prácticas laborales, mentores educativos, asesores de carrera, etc. Especial mención merece esto último; con nuestros asesores de carrera tendrás acceso a profesionales especializados en tu futura área de especialización, los cuales compartirán sus conexiones, consejos de carrera profesional, y en la mayoría de los casos su experiencia previa como estudiantes extranjeros en los Estados Unidos. En palabras de anteriores estudiantes internacionales, esta es una valiosísima adición en la industria educativa de estudios en el extranjero. Al contrario que nuestros competidores, Epro 360 es muchísimo más que un servicio de colocación. Puedes encontrar más información acerca de nuestra Red en http://www.epro360.com/network.",
	"q4" => "¿Podría atender una universidad en los Estados Unidos incluso si mi nivel de Inglés es bajo?",
	"a4" => "¡Por supuesto! Epro 360 te puede ofrecer becas para participar en los programas de ESL (Inglés como segunda lengua) en una de las muchas universidades con la que mantenemos acuerdos de colaboración. Un programa de ESL te ayudará a obtener la puntuación de TOEFL requerida por la universidad en la que deseas estudiar, además de ayudarte en tu integración en la cultura estadounidense. Este programa te resultará de gran utilidad si todavía no sabes lo que quieres estudiar o si sólo quieres mejorar tu inglés y volver a tu país tras completar el programa. El coste semestral de un  programa de ESL es normalmente inferior al de una carrera universitaria. Puedes encontrar más información acerca de nuestros programas de ESL en http://www.epro360.com/services/english-courses-esl.",
	"q5" => "¿Cuán pronto podría comenzar mi carrera universitaria en los Estados Unidos?",
	"a5" => "Tan pronto cuando recibas la lista de becas ofertadas, podrás elegir tu futura universidad. A continuación, te ayudaremos a conseguir tu visa F-1 de estudiante, lo cual te permitirá comenzar tus estudios en agosto o primavera.",
	"q6" => "¿De dónde procede el dinero de las becas ofertadas por Epro 360?",
	"a6" => "Recuerda que, desde su concepción, Estados Unidos siempre se ha caracterizado por ser un país que da la bienvenida a inmigrantes. El gobierno estadounidense es consciente de que los estudiantes internacionales son un recurso extremadamente valioso para ayudar al país a mantener su éxito. Por lo tanto, las administración pública ofrece ayuda financiera a las instituciones educativas, en su mayoría universidades públicas y privadas, para que éstas últimas puedan proporcionar becas a los estudiantes extranjeros que desean continuar sus estudios en los Estados Unidos. Además de lo anterior, a las universidades estadounidenses les encanta la diversidad que conlleva la llegada de estudiantes extranjeros a sus aulas debido al beneficio que generan en los estudiantes estadounidenses, en la comunidad, etc. Por lo tanto, algunas universidades incluso están dispuestas a invertir en becas para estudiantes extranjeros más allá de los fondos gubernamentales recibidos para este fin. Por todo lo anterior es por lo que, en muchos casos, los estudiantes extranjeros reciben ayuda financiera de forma más fácil y en cantidades superiores a los propios estudiantes estadounidenses. Recuerda que Epro 360 es una intermediaria entre el estudiante y la institución académica, y que por lo tanto, la beca que finalmente recibirás procederá de ésta última.",
	"q7" => "¿Podría transferir créditos universitarios obtenidos durante mis estudios universitarios en mi país, y así no tener que comenzar mis estudios universitarios en Estados Unidos desde cero?",
	"a7" => "La respuesta es SÍ. Como parte del proceso de aplicación, la universidad que elijas para continuar tus estudios analizará todos tus créditos universitarios obtenidos en otras instituciones. Tras completar esta evaluación, la universidad te comunicará cuántos de esos créditos podrás transferir a tu nueva carrera universitaria.",
	"q8" => "¿Cuántos créditos podría transferir a la universidad estadounidense?",
	"a8" => "Cada universidad tiene su propia política en relación a la transferencia de créditos obtenidos en otras universidades. Ni tú ni nosotros seremos capaces de cuantificar el número de créditos que podrás transferir hasta que no apliques a la universidad. Esto se debe principalmente a la gran diferencia entre los sistemas educativos en todo el mundo. La universidad que elijas se tomará su tiempo para analizar tu certificado de cursos universitarios aprobados y te comunicará cuántos de esos créditos serán transferibles. A continuación, podrás decidir si deseas continuar tu aplicación en dicha universidad o no. Por consiguiente, nunca tendrás la obligación de matricularte en esa universidad en el caso de que no estuviera de acuerdo con la cantidad de créditos que te acepten transferir. Nuestra experiencia con estudiantes, es que las universidades estadounidenses aceptan alrededor de un 50% de aquellos cursos obtenidos en universidades extranjeras. Una síntesis de este proceso sería la siguiente: Eliges la universidad en la que te gustaría continuar tus estudios universitarios → Enviamos tu expediente académico universitario traducido y certificado a la universidad  → La universidad evalúa y te comunica la cantidad de créditos que podrías transferir → Deberás aceptar o rechazar lo ofertado por la universidad.",
	"q9" => "Estoy preocupado por mi futuro profesional en este mundo tan competitivo, ¿me ayudará Epro 360 y una educación en los Estados Unidos a conseguir un trabajo y tener éxito en el futuro?",
	"a9" => "Los estudiantes que realicen nuestro programa de becas educativas y deportivas ofertado por Epro 360 tendrán, sin lugar a dudas, una ventaja competitiva frente al resto de estudiantes. Los servicios de Epro 360 los debes de percibir como una inversión en tu futuro. Una inversión que aumentará enormemente tus posibilidades de permanecer en los Estados Unidos tras completar tus estudios, sí es ésto lo que deseas. Epro 360, al igual que el resto de sus competidores, te puede confirmar que Estados Unidos es quizás uno de los mejores lugares para comenzar tu carrera profesional. Sin embargo, lo que los competidores nunca te dirán son las dificultades que tendrás para obtener una visa de trabajo y empleo. En 2013 por ejemplo, alrededor de 800.000 nuevos estudiantes extranjeros llegaron a Estados Unidos. Sin embargo, sólo había 85.000 visas H-1B disponibles para ese mismo año. Ten en cuenta que dicha visa es la principal para poder trabajar en Estados Unidos. Nuestra propia experiencia (por ejemplo, co-fundadores y líderes), confirma que el conseguir dicha visa sigue siendo posible, además de muy gratificante; sin embargo, necesitas comenzar a complementar tu futuro título universitario cuanto antes, y Epro 360 se sitúa como la mejor opción para ayudarte a conseguirlo.",
	"a10" => "En caso de que quisieras utilizar tu titulación estadounidense para conseguir un trabajo en tu país de origen, tendrás otra ventaja frente a aquellos estudiantes que se quedaron en casa. Estadísticamente, un título universitario, sobre todo uno conseguido en los Estados Unidos es un bien muy escaso, especialmente fuera de éste. De acuerdo con Tom Jelke, antiguo decano del programa Semestre en el Mar, sólo el 1% de las personas en este planeta han obtenido un título de nivel universitario. Todo lo anterior, junto con los servicios complementarios ofrecidos por Epro 360, el dominio del inglés, la experiencia de vivir en el extranjero, etc. te ofrecerán oportunidades sin precedentes.",
 	"q11" => "¿Podría trabajar en los Estados Unidos mientras estudio?",
 	"a11" => "La visa de estudiante F-1 visa te permitirá trabajar en el campus de la universidad. El Programa de trabajo y estudio ofertado por muchísimas universidades está estructurado para que el estudiante pueda compatibilizar trabajo y estudios, y esto es sin lugar a dudas, una excelente idea para aquellos estudiantes que deseen reducir el coste de su educación. Debido a que cada universidad tiene sus propias normas en materia de empleo, Epro 360 no puede prometer oportunidades de trabajo específicas con nuestras universidades colaboradoras. Dicho esto, muchos de nuestros paquetes de becas Epro 360 incluirán oportunidades de trabajo que tenemos acordadas con nuestras universidades para aquellos estudiantes que deseen compatibilizar trabajo y estudios. Podrá trabajar, siendo estudiante universitario, en los Estados Unidos, siempre y cuando siga la legislación federal de empleo. Actualmente, los estudiantes extranjeros pueden trabajar legalmente en el campus hasta 20 horas a la semana. Existen alternativas a lo anterior, dentro de los límites legales, que permitirán al estudiante trabajar fuera del campus con la visa de estudiante F-1. Epro 360 será capaz de ofrecerte servicios de consultoría en relación con todas estas cuestiones (p. ej. CPT, OPT, etc.).",

];