<?php

return [
	"title" => "Política de Privacidad",
	"modified" => "Fecha de última modificación: 1 de Mayo de 2014.",
	"p1"  => "La presente política de privacidad es aplicable a los siguientes sitios web pertenecientes y operados por Epro 360 Global Education S.L. y a todos los demás productos y servicios ofertados por la anterior, tales como el programa de Estudios Internacional Epro 360, la Red Epro 360, el programa de Donación Epro 360 Da, etc. (denominados colectivamente como \"Epro 360\").",
	"p2"  => "Mediante el uso de Epro 360, usted declara que tiene al menos la mayoría de edad en su estado o provincia de residencia, o que usted es mayor de edad en su estado o provincia de residencia y ha otorgado su consentimiento para permitir a cualquiera de sus dependientes, menores de edad, a utilizar este sitio.",
	"p3"  => "El uso de Epro 360 se rige por esta Política de Privacidad, las diversas renuncias que aparecen en nuestro sitio y nuestros Términos y Condiciones. Al visitar o usar Epro 360 usted acepta que quedará vinculado a los anteriores términos. Además, usted entiende que el método, las funciones y los servicios específicos ofrecidos por Epro 360 se pueden alterar, mejorar, eliminar o adaptar en cualquier momento mediante la sola discreción de Epro 360 y sin previo aviso necesario al usuario.",
	"p4"  => "Epro 360 está comprometido con la protección de la privacidad de sus usuarios a través de Internet. A continuación se muestra la información en referencia a nuestro continuo compromiso con el establecimiento de una gestión responsable de la información personal de los usuarios de Epro 360.",
	
	"a"   => "A. Información Personal de los Usuarios",
	"p5"  => "Durante el proceso de entrega de nuestro contenido e información a usted, podríamos recopilar cierta información personal sobre usted, como por ejemplo nombre, dirección, número de teléfono o dirección de correo electrónico. También podríamos obtener algún tipo de información personal no identificable, como por ejemplo el nombre del proveedor de servicios de Internet que utiliza para conectarse a Internet, el tipo de navegador, o el tipo de sistema operativo que utiliza (p. ej. Macintosh o Windows). La información que podríamos recopilar se utilizaría únicamente con el propósito de analizar nuestro tráfico de usuarios electrónicos y orientar los anuncios con el objetivo de hacer su navegación en nuestra página web más agradable y eficiente.",
	"p6"  => "En algunos casos, sería posible que usted proporcionase voluntariamente su información personal con el fin de inscribirse en nuestros boletines, comprar un producto o servicio, enviar una pregunta a través de nuestras diferentes plataformas que permiten interactuar con otros usuarios, etc. Esta información sería utilizada por nosotros y otros usuarios de este sitio web para responder a su solicitud. A veces podríamos combinar esta información con la información de otros usuarios y revisarlo de manera agregada para comprender el tipo de personas que utilizan nuestros sitios web. Nunca revelaremos su información personal a terceros sin su permiso, excepto en las siguientes circunstancias: i) para protegernos frente a una demanda potencial de carácter civil o penal; ii) para responder a un proceso legal o cumplir con la ley. Epro 360 no compartirá su información con terceros para fines de marketing.",
	
	"b"   => "B. Preguntas Remitidas a Epro 360",
	"p7"  => "La Red Epro 360 (“la Red”) permite al usuario crear un perfil, incluyendo su información personal. Usted puede actualizar o corregir esta información en cualquier momento. La Red permite la interacción entre sus usuarios a través de comunicaciones \"privadas\" o \"públicas\". Una comunicación \"privada\" se define como la interacción que tiene lugar entre usuarios la Red (por ejemplo empleados de Epro 360, colaboradores de Epro 360, estudiantes de Epro 360, etc.) a través de un mensaje privado. Una comunicación \"pública\" se define como la interacción que tiene lugar entre usuarios (p. ej. los detallados anteriormente) y que tiene lugar a través de cualquiera de los foros o espacios públicos (visibles al resto de usuarios) en el sitio web Epro 360. En relación con la presentación de las comunicaciones \"privadas\", toda su información personal proporcionada a Epro 360, incluyendo direcciones de correo electrónico, se oculta a todos los demás usuarios de la Red y nunca se haría pública. Sólo los administradores de la Red y el receptor de una pregunta tendrán acceso a la anterior información. Los primeros con el objetivo de administrar adecuadamente el sitio y los segundos con el objetivo de poder responder a la pregunta formulada anteriormente por el usuario. Epro 360 no revelará esta información a terceras partes sin su permiso, excepto en las siguientes circunstancias: i) frente a una demanda potencial de carácter civil o penal, o bien ii) responder a un proceso legal o para cumplir de otra manera con la ley, iii) o cuando cualquiera de los administradores y/o colaboradores pueden pensar que su pregunta puede beneficiar a otros estudiantes respondiendo a la pregunta del público. En este último caso (iii), a pesar de que el contenido de las preguntas y sus respuestas podrían hacerse visibles, la información personal tales como el correo electrónico, el nombre y la información de identificación del usuario que envió la pregunta no serán visibles para el resto de usuarios de la red.",
	"p8"  => "",
	
	"c"   => "C. Procesadores de Tarjeta de Crédito para el Pago",
	"p9"  => "Nuestros procesadores de tarjetas de crédito para el pago podrían recopilar información de usted con el fin de ser capaz de procesar sus pagos.",
	
	"d"   => "D. Cookies",
	"p10" => "Nuestros sitios web, así como la mayoría de los sitios en Internet, utilizan \"cookies\" para mejorar la experiencia del usuario en la web. En general, no podemos utilizar estas “cookies” para identificarle personalmente. El único momento en que podríamos utilizar “cookies” para identificarle personalmente, es cuando el usuario utilizase las áreas protegidas por contraseña de nuestros sitios y eligiese la opción de permitir al sistema identificar las “cookies.” Básicamente, utilizamos “cookies” para que el usuario pueda disfrutar de una manera más sencilla de nuestro sitio. El usuario debe entender que la deshabilitación de las “cookies” podría causar que algunas de las funciones de la web dejasen de estar disponibles. Si bien creemos que las “cookies” pueden mejorar su experiencia en Internet, no están en ningún momento obligados a utilizarlas. Si usted desease no aplicar las “cookies,” existe un procedimiento simple para eliminar manualmente las cookies. Por favor, consulte la documentación de ayuda de su navegador web para más información.",
	"p11" => "Además de las “cookies,” Epro 360 podría proporcionar \"contadores de visita\" al usuario a través de nuestra página web o a través de correos electrónicos. Los \"contadores de visita\" son pequeñas imágenes gráficas, que podrían no ser visibles para los usuarios de nuestro sitio, y que recopilan información sobre el uso del sitio de forma anónima. En algunos casos, los datos anónimos podrían ser transmitidos a distintas redes de publicidad. Epro 360 podría también utilizar estos \"contadores de visita\" para sus propios análisis internos, para comprender mejor la manera en que los usuarios interactúan con nuestro sitio web, o para determinar si se ha recibido un correo electrónico en particular y se abrió. También podríamos utilizar \"contadores de visita\" para potenciar nuestros esfuerzos de marketing. Por ejemplo, los \"contadores de visita\" permitirían que las redes publicitarias de terceros pudieran detectar cuando un usuario ha visitado la página web de Epro 360, y a continuación les sirviesen los anuncios de servicios ofertados por Epro 360 cuando navegasen en otro sitio web distinto.",
	
	"e"	  => "E. Abstención",
	"p12" => "Si en algún momento usted ya no desease recibir la información que originalmente nos solicitó (p. ej. boletines de noticias), por favor póngase en contacto con nosotros a través de (info@epro360.com) y eliminaremos su información de nuestro sistema. Si usted tiene alguna pregunta adicional acerca de nuestro compromiso y política en torno a la privacidad de la información personal del usuario de nuestros sitios web, por favor póngase en contacto con nosotros <a href='mailto:info@epro360.com?subject=feedback' 'Privacy Policy'>info@epro360.com</a>.",
	
	"f"   => "F. Anuncios de Terceros",
	"p13" => "Nosotros usamos compañías de publicidad de terceros para servir anuncios cuando usted visita nuestro sitio web. Estas compañías pueden usar información (sin incluir su nombre, dirección, dirección de correo electrónico o número de teléfono) sobre sus visitas a éste y otros sitios web con el fin de proporcionar anuncios sobre productos o servicios que sean de interés para usted.",
	"p14" => "Epro 360 también puede trabajar con compañías de publicidad de terceros que puedan recopilar información que usted voluntariamente proporcionase. Por favor refiérase a la política de privacidad individual y específica para cada compañía de publicidad  si desease obtener información sobre cómo gestionan la privacidad de la anterior información.",
	
	"g"   => "G. Consentimiento para la Recopilación y Procesamiento en España.",
	"p15" => "Mediante el uso de Epro 360, usted proporciona su consentimiento para que sus datos personales puedan ser transferidos y procesados ​​en España. Para todos los usuarios de Epro 360, incluso los localizados fuera de España, la información que proporcionen estará sujeta a la Ley Orgánica 15/1999, de 13 de diciembre, de Protección de datos de carácter personal. En virtud de la legislación de protección de datos, usted tiene el derecho de acceso a los datos personales que tenemos sobre usted.",
	
	"h"   => "H. Vínculos",
	"p16" => "Esta política de privacidad se aplica únicamente a la información recogida por este sitio web y no a otros sitios web que usted pueda acceder desde aquí. Epro 360 no es responsable de las prácticas de privacidad de otros sitios. Tenga en cuenta que cuando salga de este sitio, usted deberá leer las políticas de privacidad de todos aquellos sitios web que le requiriesen información personal.",
	
	"i"   => "I. Modificación de la política",
	"p17" => "Epro 360 podría modificar esta Política de Privacidad en cualquier momento sin previo aviso. El uso continuado de este sitio con posterioridad a cualquier cambio realizado en la presente política constituye su aceptación al cambio realizado por Epro 360. Por lo tanto, pedimos que revise esta Política de Privacidad con cierta frecuencia para asegurarse de que se encuentra informado de la información contenida en la política actualizada.",
	"p18" => "La presente política de privacidad podría ser presentada en distintos idiomas. El idioma español prevalece sobre todos los demás en caso de disconformidad o disputa entre el cliente y la Compañía.",
	"p19" => "Si tiene alguna pregunta sobre la presente Política de Privacidad, por favor no dude en contactar con nosotros:",
	"p20" => "Departamento Legal <br> Avenida Buhaira 18, 3, 2-B, Sevilla (41018), España. <br> <a href='mailto:info@epro360.com?subject=feedback' 'Privacy Policy'>info@epro360.com</a> "

];