<?php

return [
    "title"    => "Términos y condiciones",
    "modified" => "Fecha de última modificación: 1 de Mayo de 2014.",
    "subtitle" => "Perspectiva General",
        "p1"       => "Este sitio web es operado por Epro 360 Global Education S.L. A través del sitio, los términos \"Epro 360\", \"nosotros\" y \"nuestro\" se refieren a Epro 360 Global Education S.L. Epro 360 Global Education S.L. ofrece este sitio web, incluyendo toda la información, herramientas y servicios disponibles en este sitio para usted, el usuario, a cambio de que usted acepte todos los términos, condiciones, políticas y avisos aquí establecidos.",
        "p2"       => "Al visitar nuestro sitio y/o comprar algún producto o servicio ofertado por nosotros, acepta que quedará vinculado con Epro 360 por los siguientes términos y condiciones (\"Términos de Servicio\" o \"Condiciones\"), incluyendo los términos y condiciones y las políticas adicionales a las que pudiera hacerse referencia a través de hipervínculos mostrados claramente en nuestros sitios web. Estos Términos de Servicio se aplican a todos los usuarios de cualquiera de las páginas propiedad de Epro 360, incluyendo por ejemplo a aquellos usuarios que simplemente navegan, proveedores, clientes, comerciantes, colaboradores de contenido, etc.",
        "p3"       => "Por favor, lea estos Términos de Servicio detenidamente antes de acceder o utilizar nuestra página web. Al acceder o utilizar cualquier parte de nuestra página web, usted acepta que quedará vinculado a estas Condiciones. Si usted no está de acuerdo con todos los Términos de Servicio contenidos en este acuerdo, entonces usted podría considerar no acceder a nuestra página web y/o no utilizar nuestros productos o servicios. Si estos Términos de Servicio se considerasen una oferta, la aceptación estaría expresamente limitada a dichos Términos de Servicio.",
        "p4"       => "Cualquier función nueva o herramientas que se añadiesen a la oferta actual también estarán sujetas a los Términos de Servicio. Usted puede revisar la versión más actualizada de los Términos de Servicio en cualquier momento a través de nuestra página web. Epro 360 se reserva el derecho a actualizar, modificar o reemplazar cualquier parte de estos Términos de Servicio mediante la publicación de actualizaciones y/o cambios en nuestra página web. Es su responsabilidad el revisar esta página periódicamente para constatar que no se han producido cambios significativos que pudieran hacerle modificar su uso de nuestra página web. El acceso a nuestro sitio web después de la publicación de cualquier cambio constituye la aceptación de dichos cambios.",

    "s1"       => "Sección 1 - Condiciones generales de la Tienda Virtual",
        "p5"       => "Mediante el uso de Epro 360, usted declara que tiene al menos la mayoría de edad en su estado o provincia de residencia, o que usted es mayor de edad en su estado o provincia de residencia y ha otorgado su consentimiento para permitir a cualquiera de sus dependientes, menores de edad, a utilizar este sitio.",
        "p6"       => "Usted no puede usar nuestros productos para ningún propósito ilegal o no autorizado ni puede, en el uso del Servicio, violar cualquier ley en su jurisdicción (incluyendo pero no limitándose a las leyes de derechos de autor).",
        "p7"       => "Usted no debe transmitir ningún virus o cualquier código de naturaleza destructiva. Un incumplimiento o violación de cualquiera de los Términos de Servicio resultará en la terminación inmediata de nuestra prestación de servicios.",

    "s2"       => "Sección 2 – Condiciones Generales",
        "p8"       => "Nos reservamos el derecho a rechazar prestar el servicio a cualquier persona por cualquier motivo y en cualquier momento.",
        "p9"       => "Usted entiende que su información (excluyendo información relacionadas con tarjetas de crédito), podría transferirse sin ser encriptada y podría involucrar (a) transmisiones a través de varias redes; y (b) cambios para ajustarse y adaptarse a los requerimientos técnicos de redes o dispositivos de conexión. Es nuestro compromiso que la información relacionada con la tarjeta de crédito del usuario esté siempre cifrada durante su transmisión a través de distintas redes.",
        "p10"      => "Usted se compromete a no reproducir, duplicar, copiar, vender, revender o explotar ningún elemento que forme parte del Servicio, uso del Servicio o acceso al Servicio a través de nuestra página web sin autorización expresa por escrito de Epro 360.",
        "p11"      => "Los títulos utilizados en este acuerdo se incluyen sólo para su conveniencia y no limitarán o afectarán estos Términos de Servicio.",

    "s3"       => "Sección 3 - Exactitud, Integridad y Puntualidad de la Información",
        "p12"      => "No nos hacemos responsables si la información facilitada en este sitio no es exacta, completa o actualizada. El material se ofrece en este sitio sólo para información general y no debe confiarse en ella como la única base para tomar decisiones sin consultar fuentes de información primaria, más precisa, completa y oportuna, como por ejemplo un contrato de prestación de servicios. Cualquier confianza en el material de este sitio es bajo su propio riesgo.",
        "p13"      => "Este sitio podría contener cierta información histórica. La información histórica, necesariamente, no es actual y se proporciona únicamente para su referencia. Nos reservamos el derecho de modificar los contenidos de este sitio en cualquier momento, y al mismo tiempo no contraer ninguna obligación de actualizar contenido en este sitio. Usted acepta que es su responsabilidad revisar posibles cambios en nuestro sitio y confirmar con la empresa antes de contraer obligación alguna con Epro 360.",

    "s4"       => "Sección 4 - Las modificaciones de los Servicios y Precios",
        "p14"      => "Los precios de nuestros productos o servicios están sujetos a cambios sin previo aviso. Nos reservamos el derecho en cualquier momento de modificar o interrumpir cualquier servicio (o cualquier parte o contenido de éste) sin previo aviso en cualquier momento. Nosotros no seremos responsables ante usted ni ante ningún tercero por cualquier modificación, cambio de precio, suspensión o interrupción del Servicio, salvo que exista contrato vinculante entre el Epro 360 y el cliente. En el caso anterior, se atenderá a lo dispuesto en el contrato para resolver cualquier modificación realizada por la Empresa.",

    "s5"       => "Sección 5 - Productos y Servicios",
        "p15"      => "Ciertos productos o servicios podrían estar disponibles exclusivamente a través del sitio web. Estos productos o servicios podrían tener cantidades limitadas y estar sujetas a la devolución o cambio solamente de acuerdo con nuestra política de devoluciones.",
        "p16"      => "La Empresa ha hecho todo lo posible para mostrar con la mayor precisión posible todos los colores e imágenes de nuestros productos que aparecen publicitados en nuestra página web. No podemos garantizar que la exhibición del color en el monitor de su ordenador sea exactamente igual a la mostrada.",
        "p17"      => "Nos reservamos el derecho, pero no estamos obligados, a limitar las ventas de nuestros productos o servicios a cualquier persona, área geográfica o jurisdicción. Podríamos ejercer este derecho en casos específicos si fuese necesario. Así mismo, nos reservamos el derecho de limitar las cantidades de cualquier producto o servicio que ofrecemos. Todas las descripciones de los productos o el precio del producto están sujetos a cambio en cualquier momento sin previo aviso, a la sola discreción de nosotros.",
        "p18"      => "Nos reservamos el derecho de retirar cualquier producto o servicio en cualquier momento. Cualquier oferta de cualquier producto o servicio realizado en este sitio web se consideraría nula en aquella jurisdicción donde su comercialización se considerase prohibida. No podemos garantizar que la calidad de cualquier producto, servicio, información u otro material comprado u obtenido por usted cumpla con sus expectativas.",

    "s6"       => "Sección 6 - Precisión de la Facturación e Información de la Cuenta",
        "p19"      => "Nos reservamos el derecho de rechazar cualquier pedido que usted realice con nosotros. Podríamos, a nuestra única discreción, limitar o cancelar las cantidades compradas por persona, hogar o pedido. Estas restricciones pueden incluir pedidos realizados por o bajo la misma cuenta de cliente, la misma tarjeta de crédito, y/u órdenes que utilizasen la misma factura y/o dirección de envío. En el caso de que realizásemos un cambio o cancelación de un pedido, intentaríamos notificarle poniéndonos en contacto con usted a través de correo electrónico, dirección de facturación y/o número telefónico proporcionado en el momento de realizarse el pedido. Nos reservamos el derecho de limitar o prohibir las órdenes que, a nuestro juicio, pudieran ser interpretadas como órdenes procedentes de distribuidores, revendedores o distribuidores.",
        "p20"      => "Usted se compromete a proporcionar información personal actual, completa y precisa en relación a la compra de productos y/o servicios a través de nuestra página web con el propósito de que la Empresa pudiese poner en contacto con usted si se considerase oportuno. Usted se compromete a actualizar puntualmente su cuenta y otra información, incluyendo su dirección de correo electrónico, números de tarjetas de crédito y fechas de vencimiento, con el objetivo último de que la Empresa pueda completar sus transacciones de una manera correcta y eficiente.",

    "s7"       => "Sección 7 - Herramientas Opcionales",
        "p21"      => "Es posible que le proporcionásemos acceso a herramientas de terceros sobre los que no controlamos.",
        "p22"      => "Usted reconoce y acepta que nosotros proporcionásemos el acceso a este tipo de herramientas \"tal cual\" y \"según disponibilidad\" sin garantías, representaciones o condiciones de ningún tipo y sin ningún tipo de aval. Epro 360 no tendrá responsabilidad alguna derivada de o relacionada con el uso de herramientas de terceros, que serán siempre opcionales para el usuario de nuestra página web.",
        "p23"      => "Cualquier uso que usted hiciese de herramientas opcionales que se ofrecen a través del sitio es bajo su propio riesgo y discreción. Usted deberá asegurarse de que está familiarizado con, y aprueba, los términos en los que las herramientas de terceros sean proporcionadas.",
        "p24"      => "También es posible que, en el futuro, ofrezcamos nuevos productos y/o servicios a través del sitio web (incluyendo, el lanzamiento de nuevas herramientas y recursos). Estos productos y/o servicios nuevos también estarán sujetos a las presentes Condiciones de Servicio.",

    "s8"       => "Sección 8 - Enlaces con Terceros",
        "p25"      => "Ciertos contenidos, productos y servicios disponibles a través de Epro 360 podrían conducir a materiales de terceros a través de enlaces electrónicos o hipervínculos.",
        "p26"      => "Enlaces electrónicos o hipervínculos en nuestro sitio web podrían conducir al usuario a sitios web de terceros que no están afiliados con nosotros. No nos hacemos responsables de examinar o evaluar el contenido o exactitud de terceros y no podemos garantizar ni tendremos ningún tipo de responsabilidad en relación a cualquier material de terceros.",
        "p27"      => "No nos hacemos responsables de los daños y perjuicios relacionados con la adquisición o utilización de bienes, servicios, recursos, contenidos o cualesquier otra transacción realizada por el usuario en cualquiera de los sitios web de terceros accedidos a través de enlaces electrónicos o hipervínculos en nuestro sitio web. Por favor revise detenidamente las políticas y prácticas de terceros y asegúrese de entender su contenido antes de participar en cualquier transacción con éstos. Quejas, reclamos o preguntas con respecto a productos de terceros deberán ser dirigidas a la tercera parte.",

    "s9"       => "Sección 9 - Comentarios, Sugerencias y Otras Presentaciones por Parte del Usuario de Nuestra Página Web",
        "p28"      => "Si usted remitiese a la Empresa, independientemente de que la petición proviniese de la Empresa o no, alguna idea creativa, sugerencia, propuesta, plan, u otro material, a través de correo postal, correo electrónico u otra manera, usted acepta que la Empresa los pudiera, en cualquier momento y sin restricciones, editar, copiar, publicar, distribuir, traducir y utilizar, bajo cualquier forma y en cualquier medio. No tenemos la obligación de (1) mantener ninguno de los ejemplos mencionados anteriormente en secreto; (2) de pagar una indemnización al transmisor; o (3) responder al transmisor.",
        "p29"      => "Podemos, pero no mantenemos ninguna obligación de, monitorear, editar o eliminar el contenido que consideremos, según nuestro criterio, delictivo, ofensivo, amenazante, calumnioso, difamatorio, pornográfico, obsceno o de dudosa calidad o que viole la propiedad intelectual de cualquiera de las partes o estas Condiciones de Servicio.",
        "p30"      => "El usuario acepta que sus comentarios no violarán ningún derecho de terceros, incluyendo los derechos de autor, marca registrada, privacidad, personalidad u otro derecho personal o de propiedad. Así mismo, acepta que sus comentarios no contendrán material difamatorio o ilegal, abusivo u obsceno, o que contengan virus informáticos u otro “malware” que pudiera afectar en modo alguno el funcionamiento de los servicios prestados por Epro 360. Usted no debe utilizar una dirección de correo electrónico falsa, pretender ser alguien que no es o engañar en cuanto al origen de cualquier comentario. Usted es el único responsable de cualquier comentario que haga. No nos hacemos responsables por los comentarios publicados por usted o cualquier tercero.",

    "s10"      => "Sección 10 - Información personal",
        "p31"      => "El envío de información personal a través de la tienda virtual está gobernado por nuestra Política de Privacidad. Para ver nuestra política de privacidad por favor abra el vínculo mostrado en nuestra página web llamado “Política de Privacidad.”",

    "s11"      => "Sección 11 - Errores, Inexactitudes y Omisiones",
        "p32"      => "De vez en cuando podría existir información en nuestro sitio web que contuviese errores tipográficos, inexactitudes u omisiones que pudieran relacionarse con las descripciones de productos, precios, promociones, ofertas, los gastos de envío del producto, los tiempos de tránsito o envío, disponibilidad, etc. Nos reservamos el derecho de corregir los errores, inexactitudes u omisiones y de cambiar o actualizar la información o cancelar pedidos si alguna información relacionada con el producto o servicio ofertado en nuestro sitio web fuese inexacto en cualquier momento (incluso después de que el cliente haya confirmado su orden).",
        "p33"      => "No asumimos ninguna obligación de actualizar, corregir o aclarar información en ninguno de nuestros servicios o productos en cualquiera de nuestros sitios web, incluyendo, sin limitación, la información de precios, excepto cuando sea requerido por la ley.",

    "s12"      => "Sección 12 - Usos prohibidos",
        "p34"      => "Además de otras prohibiciones como establecidas en otras clausulas de las Condiciones del Servicio, el usuario tendrá prohibido el uso de nuestro sitio o de su contenido: (a) para cualquier propósito ilegal; (b) para solicitar a otros, llevar a cabo o participar en cualquier acto ilegal; (c) para violar regulaciones internacionales, nacionales, federales, provinciales o estatales o locales; (d) para infringir o violar nuestros derechos de propiedad intelectual o los derechos de propiedad intelectual de terceros; (e) para acosar, abusar, insultar, dañar, difamar, calumniar, desacreditar, intimidar o discriminar por razones de género, orientación sexual, religión, etnia, raza, edad, nacional o discapacidad; (f) para presentar información falsa o engañosa; (g) para cargar o transmitir virus o cualquier otro tipo de código malicioso que pueda comprometerse la funcionalidad o el funcionamiento de los servicios prestados por Epro 360 o cualquier otro sitio web relacionado; (h) para obtener o rastrear la información personal de los demás; (i) para transmitir “spam,” “phishing,” “pharm,” etc.; (j) para realizar cualquier acto cuyo propósito sea obsceno o inmoral; o (k) para interferir o burlar las medidas de seguridad de cualquier sitio web relacionado con Epro 360. Nos reservamos el derecho de suspender el uso de cualquier servicio o sitio web relacionado con Epro 360 a toda persona que violase cualquiera de los términos prohibidos en el presente acuerdo.",

    "s13"      => "Sección 13 - Exclusión de Garantías y Limitación de la Responsabilidad",
        "p35"      => "No garantizamos que el uso de nuestro servicio será ininterrumpido, puntual, seguro o libre de error.",
        "p36"      => "No garantizamos que los resultados que se puedan obtener del uso de alguno de nuestros servicios sean exactos o seguros.",
        "p37"      => "Usted acepta que con cierta frecuencia pudiésemos eliminar algún servicio por un período de tiempo indefinido o definido sin previo aviso.",
        "p38"      => "Usted acepta expresamente que el uso de, o la incapacidad de usar, cualquiera de nuestros servicios entregados a usted a través de cualquiera de nuestra página web (con excepción de lo expresamente indicado por nosotros) es bajo su propia responsabilidad.",
        "p39"      => "En ningún caso Epro 360 Global Education S.L., nuestros directores, funcionarios, empleados, afiliados, agentes, colaboradores, contratistas, personal en práctica laboral, proveedores, o prestadores de servicios serán responsables de cualquier lesión, pérdida, reclamación o cualquier daño directo o indirecto que surja del uso de cualquiera de los servicios o los productos adquiridos a través de Epro 360, o de cualquier otra reclamación relacionada de alguna manera con su uso del servicio o de cualquier producto , incluyendo, pero no limitado a, cualquier error u omisión en cualquier contenido, o cualquier pérdida o daño de cualquier tipo incurridos como resultado de la utilización del servicio o cualquier contenido (o producto) publicado. Debido a que algunos estados o jurisdicciones no permiten la exclusión o la limitación de responsabilidad por daños consecuenciales o incidentales, en tales estados o jurisdicciones, nuestra responsabilidad se limita a la extensión máxima permitida por la ley.",

    "s14"      => "Sección 14 – Indemnización",
        "p40"      => "Usted se compromete a indemnizar a Epro 360 Global Education S.L. y/o cualquiera de sus subsidiarias, empleados, socios, etc. incluyendo honorarios razonables de abogados, ante cualquier reclamo o demanda iniciado por cualquier tercero como resultado de el incumplimiento que usted pueda incurrir en relación a las Condiciones del Servicio contenidas en el presente texto, o su violación de cualquier ley o derechos sobre un tercero.",

    "s15"      => "Sección 15 – Divisibilidad",
        "p41"      => "En el caso de que cualquier clausula contenida en las Condiciones del Servicio del presente texto se considerase ilegal, nula o inejecutable, dicha clausula será aplicada hasta el máximo grado permitido por la ley aplicable, siendo considerada nula la parte no exigible por la ley aplicable.",

    "s16"      => "Sección 16 – Rescisión",
        "p42"      => "Las obligaciones y responsabilidades que las partes hayan incurrido con anterioridad a la fecha de la terminación de este acuerdo sobrevivirán tras la terminación de este acuerdo a todos los efectos.",
        "p43"      => "Estas Condiciones del Servicio se consideran efectivas a menos que se consideren concluidas por usted o por nosotros. Usted podrá rescindir estas Condiciones del Servicio en cualquier momento mediante una notificación (info@epro360.com) en la que confirme que a partir de ese momento no desea utilizar nuestros servicios, o también cuando usted deje de usar nuestro sitio de manera permanente.",
        "p44"      => "Si a nuestro juicio considerásemos o sospechamos que ha incumplido con una o varias clausulas de cualquier clausula contenida en el presente acuerdo, podríamos terminar este acuerdo en cualquier momento sin previo aviso y usted seguiría siendo responsable de todas las cantidades adeudadas hasta la fecha de la rescisión del presente acuerdo.",

    "s17"      => "Sección 17 - Acuerdo Completo",
        "p45"      => "El hecho de que nosotros para ejerzamos o hagamos valer cualquier derecho, disposición o clausula contenida en el presente acuerdo no constituirá una renuncia a tal derecho, disposición o clausula.",
        "p46"      => "Estas Condiciones del Servicio y cualquier otra política publicada en cualquiera de nuestros sitios web constituyen el acuerdo completo y el entendimiento de todas ellas entre usted y nosotros, y regirán el uso de cualquier transacción económica entre Epro  360 y usted a través de cualquiera de nuestras páginas web.",
        "p47"      => "Cualquier ambigüedad en la interpretación de estas Condiciones del Servicio no se interpretará en contra de ellas.",

    "s18"      => "Sección 18 - Ley Aplicable",
        "p48"      => "Estas Condiciones del Servicio y los acuerdos separados con lo que ponemos a su disposición servicios de terceros se regirá e interpretará de acuerdo con las leyes España.",

    "s19"      => "Sección 19 - Cambios en los Términos del Servicio",
        "p49"      => "Usted puede revisar la versión más actualizada de los Términos del Servicio en cualquier momento en esta página.",
        "p50"      => "Epro 360 podría modificar estos Términos del Servicio en cualquier momento sin previo aviso. El uso continuado de este sitio con posterioridad a cualquier cambio realizado en la presente política constituye su aceptación al cambio realizado por Epro 360. Por lo tanto, pedimos que revise estos Términos del Servicio con cierta frecuencia para asegurarse de que se encuentra informado de la información contenida en la política actualizada. <br> Los Términos del Servicio contenidos en este acuerdo podrían ser presentados en distintos idiomas. El idioma español prevalece sobre todos los demás en caso de disconformidad o disputa entre el cliente y la Compañía.",
    "s20"      => "Sección 20 - Información de Contacto",
        "p51"      => "Si tiene alguna pregunta sobre los Términos del Servicio contenidos en este acuerdo, por favor no dude en contactar con nosotros: <br> Departamento Legal <br> Avenida Buhaira 18, 3, 2-B, Sevilla (41018), España. <br> info@epro360.com"
];