<?php

return [
	"title" => "Epro 360 Backgrounder",
	"subtitle" => "Epro 360 boosts the value of international college education by taking a unique approach different from any other competitor.",
	
	"1" => "1. The value depreciation of a college degree",
	"p1" => "In the US, and the rest of the world students inhabit a world of academic inflation. Academic inflation is a term that describes the decreasing value of a college degree over time, because more people receive one. In the US for instance, many college graduates do not find a job in their chosen field of study after graduation. Part of the reason is the proliferation of college students. According to the Institute of Education Science, between 2000 and 2010, student enrollment increased 37 percent in the US, from 15.3 million to 21.0 million.",
	"p2" => "The students are operating in a rapidly growing market. In <a href='//www.usnews.com/education/best-colleges/articles/2013/11/11/us-sees-record-number-of-international-college-students'>2013</a>  alone, approximately 800,000 new international undergraduates came to study in the US, a 40% increase compared to 10 years ago.",
	"p3" => "Epro 360 believes that the problem is not the degree itself or the increasing number of students, but the lack of personal investment into oneself. Statistics from Linkedin.com have shown that those college graduates who have gained significant extracurricular experience, and those who actively invested into their personal development, get hired a lot more frequently than those who did not. Having good connections tremendously helps as well.",
	
	"2" => "2. Epro 360’s approach to combat the “academic inflation” & the competitive advantage provided by Epro 360 to the students",
	"p4" => "Epro 360’s approach to help international students become successful in the US, is a menu of extraordinary extracurricular development services. These include, but are not limited to, resume revising, personalized online marketing, internship offerings, mentorship and coaching services, which include career and personal development services, etc. Students who join the <a href='/network'> Epro 360 network </a>  will have access to full-time professionals from various industries, who can share their personal career advice, connections, and most of the times their prior experience as international students. This is an addition to simply “dropping international students off” at their chosen university, an outdated approach used by the competition. Epro 360 is more than a placement service.",
	"p5" => "Epro 360 students will have a competitive advantage compared to college graduates who did not invest in themselves. Students, who want to use their US degree to get a job in their home country are likely to have another advantage. Statistically, a college degree, especially one from the US, is an extremely scarce commodity outside of the US. According to Tom Jelke, former Executive Dean at <a href='/services/bonus-semester-at-sea' >Semester at Sea</a> says that only 1% of the people on this planet get a college level degree. Evan M. Ryan, U.S. Assistant Secretary of State for Educational and Cultural Affairs stated that, “International education promotes the relationship building and knowledge exchange between people and communities in the United States and around the world that are necessary to solve global challenges,” Taking everything together, the Epro 360 educational services, the English language proficiency, the US college degree, and the college life experience, that comes with it; it has the potential to give foreign students unprecedented opportunities.",
	"p6" => "Epro 360 factors all the prior components into its educational program and social network, because it wants to give their students more than an international degree, to be competitive either in their home country or in the US.  Utilizing all these services intelligently, Epro 360’s students can gain a better picture of themselves, which helps them tremendously to respond to our world more effectively and authentically.",
	
];