<?php

return array(
	"title" => "Privacy Policy",
	"modified" => "Last modified: May 1, 2014.",
	"p1"  => "This Privacy Policy applies to the websites owned and operated by Epro 360 Global Education S.L. and to all the other products and services that we offer, such us Epro 360 scholarships, Epro 360 Network, Epro 360 Gives, etc. (collectively referred to as \"Epro 360\").",
	"p2"  => "By using Epro 360, you represent that you are at least the age of majority in your state or province of residence, or that you are the age of majority in your state or province of residence and you have given us your consent to allow any of your minor dependents to use this site.",
	"p3"  => "The use of Epro 360 is governed by this Privacy Policy, the various disclaimers appearing on our site, and our Terms & Conditions. By visiting or using Epro 360 you agree to be bound by these terms. In addition, you understand that the specific method, features and services offered on Epro 360 may be altered, improved, removed or adapted at any time by Epro 360 in its sole discretion and without any notice.",
	"p4"  => "Epro 360 is deeply committed to protecting the privacy of Internet users. Below is information outlining our continued support for the responsible management of the users’ personal information.",
	
	"a"   => "A. Users’ Personal Information",
	"p5"  => "During the process of delivering our content and information to you, we may collect some personal information about you such as name, address, phone number, or e-mail address. We may also obtain some types of non-personally identifiable information such as the Internet Service Provider you use to connect to the Internet, your browser type, or the type of computer operating system you use (Macintosh or Windows, for example). The information collected by us is used for the purpose of analyzing our traffic and targeting ads.",
	"p6"  => "In some cases, you may voluntarily provide personal information in order to register for our newsletters, to purchase a product or service, to submit a question or respond to questions in one of our many different ways to interact with the user. This information is used by us and other users of this website to respond to your request. We may at times combine this information with other users' information and review it in an aggregate form to understand the type of individuals who use our websites. We will not disclose your personal information to third parties without your permission except in the following circumstances: i) to protect ourselves from liability; ii) to respond to a legal process or comply with the law. Epro 360 does not rent or sell its mailing list. Epro 360 will not share information about you with third parties for their direct marketing purposes.",
	
	"b"   => "B. Questions Submitted to Epro 360",
	"p7"  => "Epro 360 Network allows you to create a profile, including personal information. You may update or correct this information at any time to ensure its continued accuracy. Epro 360 Network allows interaction among its users through “private” and “public” communications.",
	"p8"  => "“Private” communication is defined as that interaction that take place among Epro 360 users (e.g. Epro 360 employees, Epro 360 collaborators, Epro 360 students, etc.) through a private message.  “Public” communication is defined as that interaction that take place among the same users, as detailed above, but taking place through any of the forums or public spaces (visible to everybody) within the Epro 360 website. In connection with the submission of “private” communications to Epro 360, all of your personal information provided to Epro 360, including email addresses, is concealed from all other users of Epro 360 and is never published as part of the Epro 360 public database. Only the Epro 360 administrators have access, for purposes of site administration only, and the recipient of a question, for purposes of responding the question only. Epro 360 will not disclose this information to third parties without your permission, except in the following circumstances: (i) to protect ourselves from liability, or (ii) to respond to legal process or to otherwise comply with the law. (iii) when either the administrators and/or the collaborators may think your question may benefit to other students by answering the question publicly.  In the latter case (iii), even though the contents of the questions and their Answers are visible, the names and identifying information of the user who submitted the question will not be visible to all users of Epro 360.",
	
	"c"   => "C. Credit Card Payment Processors",
	"p9"  => "Our Credit Card and Payment Processors may also collect information from you in order to be able to process your payments.",
	
	"d"   => "D. Cookies",
	"p10" => "Our sites, as well as most sites on the Internet, use \"cookies\" to enhance your experience on the web. Generally, we cannot use these cookies to personally identify you in any way. The only time we can use cookies to personally identify you, is when you use the password-protected areas of our sites and you chose to enable cookie identification. Basically, we use cookies to allow you to enjoy our site more and to make your visit to our site easier; disabling the cookies will cause some Epro 360 functionality to become unavailable. While we believe that cookies enhance your Internet experience, they are not required to use our sites. If you do not want the benefit of cookies, there is a simple procedure to manually delete your cookies. Please consult your web browser's Help documentation for more information.",
	"p11" => "In addition to cookies, Epro 360 may deliver \"web beacons\" through our website or through emails Epro 360 sends you. Web beacons are small graphic images that may not be visible to Site visitors that collect information about the usage of the Site on an anonymous basis. In some cases, anonymous data may be transmitted to third-party advertising networks. We may use web beacons for our own internal analytics, to better understand the ways users interact with our website, or to determine whether a particular email was received and opened. We may also use web beacons in connection with our marketing efforts. For example, web beacons allow third-party advertising networks to detect when a user has visited Epro 360's website, and then serve them ads for Epro 360's programs when they browse to another site.",
	
	"e"	  => "E. Opting Out",
	"p12" => "If at any time you no longer wish to receive the information you originally requested to receive from us (e.g. newsletters, etc.), please contact us (info@epro360.com) and we will remove your information from our system. If you have any additional questions about our dedication to consumer privacy, please contact us <a href='mailto:info@epro360.com?subject=feedback' 'Privacy Policy'>info@epro360.com</a>.",
	
	"f"   => "F. Third Party Ads",
	"p13" => "We use third-party advertising companies to serve ads when you visit our website. These companies may use information (not including your name, address, email address, or telephone number) about your visits to this and other websites in order to provide advertisements about goods and services of interest to you.",
	"p14" => "Epro 360 may also work with advertisers who may collect information that you would voluntarily provide to them. Please refer to those advertisers individual privacy policies for information on how they manage the privacy of this information.",
	
	"g"   => "G. Consent to Collection and Processing in Spain.",
	"p15" => "By using Epro 360, you consent to having your personal data transferred to and processed in Spain. For users from outside Spain, the information you provide to Epro 360 is also subject to the Organic Law 15/1999 of December 13, on Personal Data Protection. You have a right of access under data protection legislation to the personal data that we hold about you.",
	
	"h"   => "H. Links",
	"p16" => "This privacy policy applies only to information collected by this web site and not to other web sites that you may link to from here. Epro 360 is not responsible for the privacy practices of other sites. Please be aware that when you leave this site, you should read the privacy policies of each and every other website that asks you to provide personal information.",
	
	"i"   => "I. Modification of Policy",
	"p17" => "Epro 360 may modify this Privacy Policy at any time without prior notice. Continued use of this site following any change constitutes your acceptance of the change. We therefore ask you to review this Privacy Policy occasionally to ensure that you are aware of the most recent version.",
	"p18" => "This privacy policy may be presented in different languages. The Spanish language prevails over all others in the event of disagreement or dispute with the Company.",
	"p19" => "If you have any questions about this Privacy Policy, please feel free to contact us or write to us at:",
	"p20" => "Legal Department <br> Avenida Buhaira 18, 3, 2-B, Sevilla (41018), España. <br> <a href='mailto:info@epro360.com?subject=feedback' 'Privacy Policy'>info@epro360.com</a> "

);