{{ $university->name }} <br/>
{{ $university->city }} <br/>
{{ $university->state }} <br/>
{{ $university->country }} <br/>
{{ $university->zip }} <br/>
{{ $university->address }} <br/>
{{ $university->type }} <br/>
{{ $university->info }} <br/>
{{ $university->web_url }} <br/>
{{ $university->phone }} <br/>
{{ $university->email }} <br/>
{{ $university->tuition_link }} <br/>
{{ $university->admissions_link }} <br/>
{{ $university->sports_division }} <br/>
{{ $university->closest_airport }} <br/>
{{ $university->far_from_airport }} <br/>
{{ $university->housing }} <br/>
{{ $university->postal }} <br/>
{{ $university->years }} <br/>
{{ $university->settings }} <br/>
{{ $university->tuition }} <br/>
{{ $university->created_at }} <br/>
