<?php


class CountriesTableSeeder extends Seeder {

    public function run()
    {
        Country::truncate();

        $countries = [
            // Africa
            ["name" => "Algeria", "continent_id" => 1, "phonecode" => 213],
            ["name" => "Angola", "continent_id" => 1, "phonecode" => 244],
            ["name" => "Benin", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Botswana", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Burkina", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Burundi", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Cameroon", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Cape Verde", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Central African Republic", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Chad", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Comoros", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Congo", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Congo, Democratic Republic of", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Djibouti", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Egypt", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Equatorial Guinea", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Eritrea", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Ethiopia", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Gabon", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Gambia", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Ghana", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Guinea", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Guinea-Bissau", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Ivory Coast", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Kenya", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Lesotho", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Liberia", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Libya", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Madagascar", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Malawi", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Mali", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Mauritania", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Mauritius", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Morocco", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Mozambique", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Namibia", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Niger", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Nigeria", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Rwanda", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Sao Tome and Principe", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Senegal", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Seychelles", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Sierra Leone", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Somalia", "continent_id" => 1, "phonecode" => 0],
            ["name" => "South Africa", "continent_id" => 1, "phonecode" => 0],
            ["name" => "South Sudan", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Sudan", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Swaziland", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Tanzania", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Togo", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Tunisia", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Uganda", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Zambia", "continent_id" => 1, "phonecode" => 0],
            ["name" => "Zimbabwe", "continent_id" => 1, "phonecode" => 0],

            // Asia
            ["name" => "Afghanistan", "continent_id" => 2, "phonecode" => 93],
            ["name" => "Bahrain", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Bangladesh", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Bhutan", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Brunei", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Burma (Myanmar)", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Cambodia", "continent_id" => 2, "phonecode" => 0],
            ["name" => "China", "continent_id" => 2, "phonecode" => 0],
            ["name" => "East Timor", "continent_id" => 2, "phonecode" => 0],
            ["name" => "India", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Indonesia", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Iran", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Iraq", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Israel", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Japan", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Jordan", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Kazakhstan", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Korea, North", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Korea, South", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Kuwait", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Kyrgyzstan", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Laos", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Lebanon", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Malaysia", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Maldives", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Mongolia", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Nepal", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Oman", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Pakistan", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Philippines", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Qatar", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Russian Federation", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Saudi Arabia", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Singapore", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Sri Lanka", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Syria", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Tajikistan", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Thailand", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Turkey", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Turkmenistan", "continent_id" => 2, "phonecode" => 0],
            ["name" => "United Arab Emirates", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Uzbekistan", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Vietnam", "continent_id" => 2, "phonecode" => 0],
            ["name" => "Yemen", "continent_id" => 2, "phonecode" => 0],

            // Europe    
            ["name" => "Albania", "continent_id" => 3, "phonecode" => 355],
            ["name" => "Andorra", "continent_id" => 3, "phonecode" => 376],
            ["name" => "Armenia", "continent_id" => 3, "phonecode" => 374],
            ["name" => "Austria", "continent_id" => 3, "phonecode" => 43],
            ["name" => "Azerbaijan", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Belarus", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Belgium", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Bosnia and Herzegovina", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Bulgaria", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Croatia", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Cyprus", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Czech Republic", "continent_id" => 3, "phonecode" => 420],
            ["name" => "Denmark", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Estonia", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Finland", "continent_id" => 3, "phonecode" => 0],
            ["name" => "France", "continent_id" => 3, "phonecode" => 33],
            ["name" => "Georgia", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Germany", "continent_id" => 3, "phonecode" => 49],
            ["name" => "Greece", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Hungary", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Iceland", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Ireland", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Italy", "continent_id" => 3, "phonecode" => 39],
            ["name" => "Latvia", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Liechtenstein", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Lithuania", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Luxembourg", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Macedonia", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Malta", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Moldova", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Monaco", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Montenegro", "continent_id" => 3, "phonecode" => 31],
            ["name" => "Netherlands", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Norway", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Poland", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Portugal", "continent_id" => 3, "phonecode" => 351],
            ["name" => "Romania", "continent_id" => 3, "phonecode" => 0],
            ["name" => "San Marino", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Serbia", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Slovakia", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Slovenia", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Spain", "continent_id" => 3, "phonecode" => 34],
            ["name" => "Sweden", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Switzerland", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Ukraine", "continent_id" => 3, "phonecode" => 0],
            ["name" => "United Kingdom", "continent_id" => 3, "phonecode" => 0],
            ["name" => "Vatican City", "continent_id" => 3, "phonecode" => 0],

            // North America
            ["name" => "Antigua and Barbuda", "continent_id" => 4, "phonecode" => 1268],
            ["name" => "Bahamas", "continent_id" => 4, "phonecode" => 1242],
            ["name" => "Barbados", "continent_id" => 4, "phonecode" => 1246],
            ["name" => "Belize", "continent_id" => 4, "phonecode" => 501],
            ["name" => "Canada", "continent_id" => 4, "phonecode" => 1],
            ["name" => "Costa Rica", "continent_id" => 4, "phonecode" => 506],
            ["name" => "Cuba", "continent_id" => 4, "phonecode" => 53],
            ["name" => "Dominica", "continent_id" => 4, "phonecode" => 1767],
            ["name" => "Dominican Republic", "continent_id" => 4, "phonecode" => 1809],
            ["name" => "El Salvador", "continent_id" => 4, "phonecode" => 503],
            ["name" => "Grenada", "continent_id" => 4, "phonecode" => 1473],
            ["name" => "Guatemala", "continent_id" => 4, "phonecode" => 502],
            ["name" => "Haiti", "continent_id" => 4, "phonecode" => 509],
            ["name" => "Honduras", "continent_id" => 4, "phonecode" => 504],
            ["name" => "Jamaica", "continent_id" => 4, "phonecode" => 1876],
            ["name" => "Mexico", "continent_id" => 4, "phonecode" => 52],
            ["name" => "Nicaragua", "continent_id" => 4, "phonecode" => 505],
            ["name" => "Panama", "continent_id" => 4, "phonecode" => 507],
            ["name" => "Saint Kitts and Nevis", "continent_id" => 4, "phonecode" => 1869],
            ["name" => "Saint Lucia", "continent_id" => 4, "phonecode" => 1758],
            ["name" => "Saint Vincent and the Grenadines", "continent_id" => 4, "phonecode" => 1784],
            ["name" => "Trinidad and Tobago", "continent_id" => 4, "phonecode" => 1868],
            ["name" => "United States", "continent_id" => 4, "phonecode" => 1],

            // South America
            ["name" => "Argentina", "continent_id" => 5, "phonecode" => 54],
            ["name" => "Bolivia", "continent_id" => 5, "phonecode" => 591],
            ["name" => "Brazil", "continent_id" => 5, "phonecode" => 55],
            ["name" => "Chile", "continent_id" => 5, "phonecode" => 56],
            ["name" => "Colombia", "continent_id" => 5, "phonecode" => 57],
            ["name" => "Ecuador", "continent_id" => 5, "phonecode" => 593],
            ["name" => "Guyana", "continent_id" => 5, "phonecode" => 592],
            ["name" => "Paraguay", "continent_id" => 5, "phonecode" => 595],
            ["name" => "Peru", "continent_id" => 5, "phonecode" => 51],
            ["name" => "Suriname", "continent_id" => 5, "phonecode" => 597],
            ["name" => "Uruguay", "continent_id" => 5, "phonecode" => 598],
            ["name" => "Venezuela", "continent_id" => 5, "phonecode" => 58],

            // Oceania
            ["name" => "Australia", "continent_id" => 6, "phonecode" => 0],
            ["name" => "Fiji", "continent_id" => 6, "phonecode" => 0],
            ["name" => "Kiribati", "continent_id" => 6, "phonecode" => 0],
            ["name" => "Marshall Islands", "continent_id" => 6, "phonecode" => 0],
            ["name" => "Micronesia", "continent_id" => 6, "phonecode" => 0],
            ["name" => "Nauru", "continent_id" => 6, "phonecode" => 0],
            ["name" => "New Zealand", "continent_id" => 6, "phonecode" => 0],
            ["name" => "Palau", "continent_id" => 6, "phonecode" => 0],
            ["name" => "Papua New Guinea", "continent_id" => 6, "phonecode" => 0],
            ["name" => "Samoa", "continent_id" => 6, "phonecode" => 0],
            ["name" => "Solomon Islands", "continent_id" => 6, "phonecode" => 0],
            ["name" => "Tonga", "continent_id" => 6, "phonecode" => 0],
            ["name" => "Tuvalu", "continent_id" => 6, "phonecode" => 0],
            ["name" => "Vanuatu", "continent_id" => 6, "phonecode" => 0],

        ];

        foreach($countries as $country)
        {
            Country::create([
                "name" => $country["name"],
                "phonecode" => $country["phonecode"],
                "continent_id" => $country["continent_id"]
            ]);
        }
    }

}